# If Y2W was useful to you ☕

ko_fi: fedevgonzalez
custom: [
  "https://cafecito.app/fedevgonzalez",
  "https://github.com/fedevgonzalez/youtube-to-w2g#-support"
]

# Y2W is a labor of love, but coffee helps too ☕
# From Argentina 🇦🇷 to the world 🌎